[package]
name = "geomify"
version = "0.1.0"
authors = ["phil <phil.j.ellison@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.21"
rand = "0.7"
structopt = "0.2"
