[package]
name = "geomify"
version = "0.1.0"
authors = ["phil <phil.j.ellison@gmail.com>"]
edition = "2018"

[dependencies]
image = "0.21"
imageproc = { git = "https://github.com/image-rs/imageproc" }
log = "0.4.6"
rand = "0.7"
simplelog = "0.6"
structopt = "0.2"
